### ISSUE TITLE
bug, no effect!!

### ISSUE THREAD

**Issue by abbycin** [4679/vimrc#1]
platform: openSUSE Tumbleweed x64
vim version: 7.4 (2013 Aug 10)

## before creating `.vimrc`
![1](https://cloud.githubusercontent.com/assets/6814167/11930904/cac9f460-a822-11e5-9a9c-f263c11b2c7a.png)

## after using your `vimrc`
![2](https://cloud.githubusercontent.com/assets/6814167/11930932/2591e4de-a823-11e5-85db-94f3fc1eb8fb.png)

**Comment by 4679** [comment]
Sir.It's worked fine.


你在逗我吗

**Comment by mealayaria** [comment]
然而并没什么卵用
