### ISSUE TITLE
可能会造成之前的vim 配置文件丢失

### ISSUE THREAD

**Issue by Arondight** [4679/vimrc#3]
楼主有没有想过，安装指令执行两次，之前的vim 配置文件 就没了 没了 了

**Comment by 4679** [comment]
有自己的配置用这个干嘛(`ε´(つ*⊂)
再说为何要运行两次

**Comment by Arondight** [comment]
安装命令多执行几次是很正常的啊

**Comment by 4679** [comment]
我有时间去加个判断(=ﾟωﾟ)=

**Comment by Arondight** [comment]
你只需要在目标文件名中加上一个绝对不会重复的东西就可以了，例如date 指令的输出

**Comment by Arondight** [comment]
你只需要在目标文件名中加上一个绝对不会重复的东西就可以了，例如date 指令的输出

**Comment by Arondight** [comment]
你只需要在目标文件名中加上一个绝对不会重复的东西就可以了，例如date 指令的输出

**Comment by Arondight** [comment]
你只需要在目标文件名中加上一个绝对不会重复的东西就可以了，例如date 指令的输出……

**Comment by Arondight** [comment]
你只需要在目标文件名中加上一个绝对不会重复的东西就可以了，例如date 指令的输出……

**Comment by Arondight** [comment]
你只需要在目标文件名中加上一个绝对不会重复的东西就可以了，例如date 指令的输出……

**Comment by 4679** [comment]
对哦 (`ε´(つ*⊂)

**Comment by 4679** [comment]
ok了
